name: MiniBosses
main: MiniBosses\Main
description: Adds very customisable Bosses
version: 1.0.0
api: [2.1.0, 3.0.0-ALPHA3]
load: POSTWORLD
author: ace
commands:
  minibosses:
    description: control MiniBosses
    usage: "/minibosses <create/delete>"
    permission: minibosses.command
permissions:
  minibosses.command:
    description: "Allows usage of the minibosses command."
    default: op