name: MiniBosses
main: diamondgold\MiniBosses\Main
description: Adds very customisable Bosses
version: 3.2.4
api: 4.10.0
load: POSTWORLD
author: diamond-gold (ace)
website: https://github.com/diamond-gold/MiniBosses
commands:
  minibosses:
    description: Manage MiniBosses
    usage: "/minibosses list OR /minibosses create <networkId: EntityType> <name: message> OR /minibosses spawn <name: message> OR /minibosses despawn <name: message> OR /minibosses delete <name: message> OR /minibosses toggleEnabled <name: message>"
    permission: minibosses.command
permissions:
  minibosses.command:
    description: "Allows usage of the minibosses command."
    default: op