name: MiniBosses
main: MiniBosses\Main
description: Adds very customisable Bosses
version: 3.0.0
api: 4.3.0
load: POSTWORLD
author: ace
commands:
  minibosses:
    description: Manage MiniBosses
    usage: "/minibosses list OR /minibosses create <networkId: EntityType> <name: message> OR /minibosses spawn <name: message> OR /minibosses delete <name: message>"
    permission: minibosses.command
permissions:
  minibosses.command:
    description: "Allows usage of the minibosses command."
    default: op